// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class CodeUnit
{
    public Guid UnitId { get; set; }

    public Guid SubmissionId { get; set; }

    public Guid FileId { get; set; }

    public string UnitKind { get; set; }

    public string UnitKey { get; set; }

    public int? StartLine { get; set; }

    public int? EndLine { get; set; }

    public string Content { get; set; }

    public byte[] ContentHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual CodeEmbedding CodeEmbedding { get; set; }

    public virtual CodeFile File { get; set; }

    public virtual ICollection<MatchResult> MatchResultSrcUnits { get; set; } = new List<MatchResult>();

    public virtual ICollection<MatchResult> MatchResultTgtUnits { get; set; } = new List<MatchResult>();

    public virtual Submission Submission { get; set; }
}