// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class CodeEmbedding
{
    public Guid UnitId { get; set; }

    public Guid SubmissionId { get; set; }

    public string ModelName { get; set; }

    public int EmbeddingDimension { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Submission Submission { get; set; }

    public virtual CodeUnit Unit { get; set; }
}