// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class CodeFile
{
    public Guid FileId { get; set; }

    public Guid SubmissionId { get; set; }

    public string RelPath { get; set; }

    public string Language { get; set; }

    public int? LineCount { get; set; }

    public byte[] FileHash { get; set; }

    public long? FileSize { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CodeUnit> CodeUnits { get; set; } = new List<CodeUnit>();

    public virtual Submission Submission { get; set; }
}