// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class DuplicateDetection
{
    public long Id { get; set; }

    public Guid ExamId { get; set; }

    public Guid? ExaminerId { get; set; }

    public Guid SubmissionId1 { get; set; }

    public Guid SubmissionId2 { get; set; }

    public Guid StudentId1 { get; set; }

    public Guid StudentId2 { get; set; }

    public decimal? VectorScore { get; set; }

    public bool IsDuplicate { get; set; }

    public string ThresholdUsed { get; set; }

    public string MatchedUnits { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Examiner Examiner { get; set; }

    public virtual Submission SubmissionId1Navigation { get; set; }

    public virtual Submission SubmissionId2Navigation { get; set; }
}