// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class Examiner
{
    public Guid ExaminerId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<DuplicateDetection> DuplicateDetections { get; set; } = new List<DuplicateDetection>();

    public virtual ICollection<MatchResult> MatchResults { get; set; } = new List<MatchResult>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}