// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class MatchResult
{
    public long Id { get; set; }

    public Guid ExamId { get; set; }

    public Guid? ExaminerId { get; set; }

    public Guid SrcUnitId { get; set; }

    public Guid TgtUnitId { get; set; }

    public Guid SrcSubmissionId { get; set; }

    public Guid TgtSubmissionId { get; set; }

    public string Method { get; set; }

    public decimal Score { get; set; }

    public decimal? Distance { get; set; }

    public string Detail { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Examiner Examiner { get; set; }

    public virtual Submission SrcSubmission { get; set; }

    public virtual CodeUnit SrcUnit { get; set; }

    public virtual Submission TgtSubmission { get; set; }

    public virtual CodeUnit TgtUnit { get; set; }
}