// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class Submission
{
    public Guid SubmissionId { get; set; }

    public Guid ExamId { get; set; }

    public Guid StudentId { get; set; }

    public Guid? ExaminerId { get; set; }

    public string StorageKey { get; set; }

    public string Status { get; set; }

    public int? TotalFiles { get; set; }

    public int? TotalLines { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? AnalyzedAt { get; set; }

    public virtual ICollection<CodeEmbedding> CodeEmbeddings { get; set; } = new List<CodeEmbedding>();

    public virtual ICollection<CodeFile> CodeFiles { get; set; } = new List<CodeFile>();

    public virtual ICollection<CodeUnit> CodeUnits { get; set; } = new List<CodeUnit>();

    public virtual ICollection<DuplicateDetection> DuplicateDetectionSubmissionId1Navigations { get; set; } = new List<DuplicateDetection>();

    public virtual ICollection<DuplicateDetection> DuplicateDetectionSubmissionId2Navigations { get; set; } = new List<DuplicateDetection>();

    public virtual Exam Exam { get; set; }

    public virtual Examiner Examiner { get; set; }

    public virtual ICollection<MatchResult> MatchResultSrcSubmissions { get; set; } = new List<MatchResult>();

    public virtual ICollection<MatchResult> MatchResultTgtSubmissions { get; set; } = new List<MatchResult>();
}