// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Worker_Repo.Models;

public partial class WhitelistUnit
{
    public long Id { get; set; }

    public Guid ExamId { get; set; }

    public string UnitKey { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Exam Exam { get; set; }
}