// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PRN232_GradingSystem_Worker_Repo.Models;

namespace PRN232_GradingSystem_Worker_Repo.DBContext;

public partial class PRN232_Grading_System_GradingContext : DbContext
{
    public PRN232_Grading_System_GradingContext(DbContextOptions<PRN232_Grading_System_GradingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CodeEmbedding> CodeEmbeddings { get; set; }

    public virtual DbSet<CodeFile> CodeFiles { get; set; }

    public virtual DbSet<CodeUnit> CodeUnits { get; set; }

    public virtual DbSet<DuplicateDetection> DuplicateDetections { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Examiner> Examiners { get; set; }

    public virtual DbSet<MatchResult> MatchResults { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<WhitelistUnit> WhitelistUnits { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("uuid-ossp")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<CodeEmbedding>(entity =>
        {
            entity.HasKey(e => e.UnitId).HasName("code_embedding_pkey");

            entity.ToTable("code_embedding");

            entity.HasIndex(e => e.SubmissionId, "idx_emb_submission");

            entity.Property(e => e.UnitId)
                .ValueGeneratedNever()
                .HasColumnName("unit_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.EmbeddingDimension).HasColumnName("embedding_dimension");
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasColumnName("model_name");
            entity.Property(e => e.SubmissionId).HasColumnName("submission_id");

            entity.HasOne(d => d.Submission).WithMany(p => p.CodeEmbeddings)
                .HasForeignKey(d => d.SubmissionId)
                .HasConstraintName("code_embedding_submission_id_fkey");

            entity.HasOne(d => d.Unit).WithOne(p => p.CodeEmbedding)
                .HasForeignKey<CodeEmbedding>(d => d.UnitId)
                .HasConstraintName("code_embedding_unit_id_fkey");
        });

        modelBuilder.Entity<CodeFile>(entity =>
        {
            entity.HasKey(e => e.FileId).HasName("code_file_pkey");

            entity.ToTable("code_file");

            entity.HasIndex(e => e.RelPath, "idx_file_relpath");

            entity.HasIndex(e => e.SubmissionId, "idx_file_submission");

            entity.Property(e => e.FileId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("file_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.FileHash).HasColumnName("file_hash");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.Language).HasColumnName("language");
            entity.Property(e => e.LineCount).HasColumnName("line_count");
            entity.Property(e => e.RelPath)
                .IsRequired()
                .HasColumnName("rel_path");
            entity.Property(e => e.SubmissionId).HasColumnName("submission_id");

            entity.HasOne(d => d.Submission).WithMany(p => p.CodeFiles)
                .HasForeignKey(d => d.SubmissionId)
                .HasConstraintName("code_file_submission_id_fkey");
        });

        modelBuilder.Entity<CodeUnit>(entity =>
        {
            entity.HasKey(e => e.UnitId).HasName("code_unit_pkey");

            entity.ToTable("code_unit");

            entity.HasIndex(e => e.FileId, "idx_unit_file");

            entity.HasIndex(e => e.UnitKey, "idx_unit_key");

            entity.HasIndex(e => e.SubmissionId, "idx_unit_submission");

            entity.Property(e => e.UnitId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("unit_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.ContentHash).HasColumnName("content_hash");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.EndLine).HasColumnName("end_line");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.StartLine).HasColumnName("start_line");
            entity.Property(e => e.SubmissionId).HasColumnName("submission_id");
            entity.Property(e => e.UnitKey)
                .IsRequired()
                .HasColumnName("unit_key");
            entity.Property(e => e.UnitKind)
                .IsRequired()
                .HasColumnName("unit_kind");

            entity.HasOne(d => d.File).WithMany(p => p.CodeUnits)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("code_unit_file_id_fkey");

            entity.HasOne(d => d.Submission).WithMany(p => p.CodeUnits)
                .HasForeignKey(d => d.SubmissionId)
                .HasConstraintName("code_unit_submission_id_fkey");
        });

        modelBuilder.Entity<DuplicateDetection>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("duplicate_detection_pkey");

            entity.ToTable("duplicate_detection");

            entity.HasIndex(e => new { e.ExamId, e.ExaminerId, e.VectorScore }, "idx_dup_vector_desc").IsDescending(false, false, true);

            entity.HasIndex(e => new { e.ExamId, e.ExaminerId, e.SubmissionId1, e.SubmissionId2 }, "uq_dup_pair").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ExamId).HasColumnName("exam_id");
            entity.Property(e => e.ExaminerId).HasColumnName("examiner_id");
            entity.Property(e => e.IsDuplicate)
                .HasDefaultValue(false)
                .HasColumnName("is_duplicate");
            entity.Property(e => e.MatchedUnits)
                .HasColumnType("jsonb")
                .HasColumnName("matched_units");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.StudentId1).HasColumnName("student_id1");
            entity.Property(e => e.StudentId2).HasColumnName("student_id2");
            entity.Property(e => e.SubmissionId1).HasColumnName("submission_id1");
            entity.Property(e => e.SubmissionId2).HasColumnName("submission_id2");
            entity.Property(e => e.ThresholdUsed).HasColumnName("threshold_used");
            entity.Property(e => e.VectorScore)
                .HasPrecision(6, 5)
                .HasColumnName("vector_score");

            entity.HasOne(d => d.Exam).WithMany(p => p.DuplicateDetections)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("duplicate_detection_exam_id_fkey");

            entity.HasOne(d => d.Examiner).WithMany(p => p.DuplicateDetections)
                .HasForeignKey(d => d.ExaminerId)
                .HasConstraintName("duplicate_detection_examiner_id_fkey");

            entity.HasOne(d => d.SubmissionId1Navigation).WithMany(p => p.DuplicateDetectionSubmissionId1Navigations)
                .HasForeignKey(d => d.SubmissionId1)
                .HasConstraintName("duplicate_detection_submission_id1_fkey");

            entity.HasOne(d => d.SubmissionId2Navigation).WithMany(p => p.DuplicateDetectionSubmissionId2Navigations)
                .HasForeignKey(d => d.SubmissionId2)
                .HasConstraintName("duplicate_detection_submission_id2_fkey");
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.ExamId).HasName("exam_pkey");

            entity.ToTable("exam");

            entity.HasIndex(e => e.Code, "exam_code_key").IsUnique();

            entity.Property(e => e.ExamId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("exam_id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Title).HasColumnName("title");
        });

        modelBuilder.Entity<Examiner>(entity =>
        {
            entity.HasKey(e => e.ExaminerId).HasName("examiner_pkey");

            entity.ToTable("examiner");

            entity.HasIndex(e => e.Code, "examiner_code_key").IsUnique();

            entity.Property(e => e.ExaminerId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("examiner_id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
        });

        modelBuilder.Entity<MatchResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("match_result_pkey");

            entity.ToTable("match_result");

            entity.HasIndex(e => new { e.ExamId, e.ExaminerId }, "idx_match_exam_examiner");

            entity.HasIndex(e => new { e.ExamId, e.SrcSubmissionId }, "idx_match_exam_srcsub");

            entity.HasIndex(e => new { e.ExamId, e.TgtSubmissionId }, "idx_match_exam_tgtsub");

            entity.HasIndex(e => new { e.ExamId, e.Score }, "idx_match_score_desc").IsDescending(false, true);

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Detail)
                .HasColumnType("jsonb")
                .HasColumnName("detail");
            entity.Property(e => e.Distance)
                .HasPrecision(6, 5)
                .HasColumnName("distance");
            entity.Property(e => e.ExamId).HasColumnName("exam_id");
            entity.Property(e => e.ExaminerId).HasColumnName("examiner_id");
            entity.Property(e => e.Method)
                .IsRequired()
                .HasDefaultValueSql("'vector'::text")
                .HasColumnName("method");
            entity.Property(e => e.Score)
                .HasPrecision(6, 5)
                .HasColumnName("score");
            entity.Property(e => e.SrcSubmissionId).HasColumnName("src_submission_id");
            entity.Property(e => e.SrcUnitId).HasColumnName("src_unit_id");
            entity.Property(e => e.TgtSubmissionId).HasColumnName("tgt_submission_id");
            entity.Property(e => e.TgtUnitId).HasColumnName("tgt_unit_id");

            entity.HasOne(d => d.Exam).WithMany(p => p.MatchResults)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("match_result_exam_id_fkey");

            entity.HasOne(d => d.Examiner).WithMany(p => p.MatchResults)
                .HasForeignKey(d => d.ExaminerId)
                .HasConstraintName("match_result_examiner_id_fkey");

            entity.HasOne(d => d.SrcSubmission).WithMany(p => p.MatchResultSrcSubmissions)
                .HasForeignKey(d => d.SrcSubmissionId)
                .HasConstraintName("match_result_src_submission_id_fkey");

            entity.HasOne(d => d.SrcUnit).WithMany(p => p.MatchResultSrcUnits)
                .HasForeignKey(d => d.SrcUnitId)
                .HasConstraintName("match_result_src_unit_id_fkey");

            entity.HasOne(d => d.TgtSubmission).WithMany(p => p.MatchResultTgtSubmissions)
                .HasForeignKey(d => d.TgtSubmissionId)
                .HasConstraintName("match_result_tgt_submission_id_fkey");

            entity.HasOne(d => d.TgtUnit).WithMany(p => p.MatchResultTgtUnits)
                .HasForeignKey(d => d.TgtUnitId)
                .HasConstraintName("match_result_tgt_unit_id_fkey");
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("submission_pkey");

            entity.ToTable("submission");

            entity.HasIndex(e => new { e.ExamId, e.ExaminerId }, "idx_submission_exam_examiner");

            entity.HasIndex(e => new { e.ExamId, e.StudentId }, "uq_submission_exam_student").IsUnique();

            entity.Property(e => e.SubmissionId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("submission_id");
            entity.Property(e => e.AnalyzedAt).HasColumnName("analyzed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ExamId).HasColumnName("exam_id");
            entity.Property(e => e.ExaminerId).HasColumnName("examiner_id");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'processed'::text")
                .HasColumnName("status");
            entity.Property(e => e.StorageKey)
                .IsRequired()
                .HasColumnName("storage_key");
            entity.Property(e => e.StudentId).HasColumnName("student_id");
            entity.Property(e => e.TotalFiles)
                .HasDefaultValue(0)
                .HasColumnName("total_files");
            entity.Property(e => e.TotalLines)
                .HasDefaultValue(0)
                .HasColumnName("total_lines");

            entity.HasOne(d => d.Exam).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("submission_exam_id_fkey");

            entity.HasOne(d => d.Examiner).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.ExaminerId)
                .HasConstraintName("submission_examiner_id_fkey");
        });

        modelBuilder.Entity<WhitelistUnit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("whitelist_unit_pkey");

            entity.ToTable("whitelist_unit");

            entity.HasIndex(e => new { e.ExamId, e.UnitKey }, "whitelist_unit_exam_id_unit_key_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ExamId).HasColumnName("exam_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.UnitKey)
                .IsRequired()
                .HasColumnName("unit_key");

            entity.HasOne(d => d.Exam).WithMany(p => p.WhitelistUnits)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("whitelist_unit_exam_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}